USE [master]
GO

IF DB_ID('HRD') IS NULL
CREATE DATABASE [HRD] ON  PRIMARY 
( NAME = N'HRD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLDB\MSSQL\DATA\HRD.mdf' , SIZE = 146624KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HRD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLDB\MSSQL\DATA\HRD_log.LDF' , SIZE = 35712KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [HRD] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HRD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HRD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HRD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HRD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HRD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HRD] SET ARITHABORT OFF 
GO

ALTER DATABASE [HRD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HRD] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [HRD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HRD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HRD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HRD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HRD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HRD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HRD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HRD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HRD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HRD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HRD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HRD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HRD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HRD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HRD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HRD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HRD] SET  READ_WRITE 
GO

ALTER DATABASE [HRD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HRD] SET  MULTI_USER 
GO

ALTER DATABASE [HRD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HRD] SET DB_CHAINING OFF 
GO

